/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Questao_03;

/**
 *
 * @author jg_la
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_eixox = new javax.swing.JLabel();
        lb_eixoy = new javax.swing.JLabel();
        tf_eixox = new javax.swing.JTextField();
        tf_eixoy = new javax.swing.JTextField();
        btn_avaliar = new javax.swing.JButton();
        lb_posicao = new javax.swing.JLabel();
        chk_incideX = new javax.swing.JCheckBox();
        chk_incideY = new javax.swing.JCheckBox();
        chk_quadrante1 = new javax.swing.JCheckBox();
        chk_quadrante2 = new javax.swing.JCheckBox();
        chk_quadrante3 = new javax.swing.JCheckBox();
        chk_quadrante4 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_eixox.setText("Eixo X:");

        lb_eixoy.setText("Eixo Y:");

        btn_avaliar.setText("Avaliar");
        btn_avaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPressedAvaliar(evt);
            }
        });

        lb_posicao.setText("Posição:");

        chk_incideX.setText("Incide sobre o Eixo X");
        chk_incideX.setEnabled(false);
        chk_incideX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_incideXActionPerformed(evt);
            }
        });

        chk_incideY.setText("Incide sobre o Eixo Y");
        chk_incideY.setEnabled(false);

        chk_quadrante1.setText("No 1° Quadrante");
        chk_quadrante1.setEnabled(false);

        chk_quadrante2.setText("No 2° Quadrante");
        chk_quadrante2.setEnabled(false);
        chk_quadrante2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_quadrante2ActionPerformed(evt);
            }
        });

        chk_quadrante3.setText("No 3° Quadrante");
        chk_quadrante3.setEnabled(false);
        chk_quadrante3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_quadrante3ActionPerformed(evt);
            }
        });

        chk_quadrante4.setText("No 4° Quadrante");
        chk_quadrante4.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_posicao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_eixoy, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_eixoy, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_eixox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_eixox)))
                        .addGap(56, 56, 56)
                        .addComponent(btn_avaliar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chk_incideX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chk_incideY, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chk_quadrante1)
                            .addComponent(chk_quadrante2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chk_quadrante3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chk_quadrante4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_eixox)
                            .addComponent(tf_eixox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_eixoy)
                            .addComponent(tf_eixoy)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_avaliar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(lb_posicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chk_incideX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_incideY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_quadrante1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_quadrante2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_quadrante3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_quadrante4)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk_incideXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_incideXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_incideXActionPerformed

    private void chk_quadrante2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_quadrante2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_quadrante2ActionPerformed

    private void chk_quadrante3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_quadrante3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_quadrante3ActionPerformed

    private void onPressedAvaliar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPressedAvaliar
        chk_quadrante1.setSelected(false);
        chk_quadrante2.setSelected(false);
        chk_quadrante3.setSelected(false);
        chk_quadrante4.setSelected(false);
        chk_incideX.setSelected(false);
        chk_incideY.setSelected(false);
        
        Ponto ponto = new Ponto(Integer.parseInt(tf_eixox.getText()),Integer.parseInt(tf_eixoy.getText()));
      
        switch(ponto.identificarQuadrante()){
            case PRIMEIRO:
                chk_quadrante1.setSelected(true);
                break;
            case SEGUNDO:
                chk_quadrante2.setSelected(true);
                break;
            case TERCEIRO:
                chk_quadrante3.setSelected(true);
                break;
            case QUARTO:
                chk_quadrante4.setSelected(true);
                break;
            case NENHUM:
                if(ponto.getX() == 0)
                    chk_incideX.setSelected(true);
                if(ponto.getY()==0)
                    chk_incideY.setSelected(true);
        }
    }//GEN-LAST:event_onPressedAvaliar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_avaliar;
    private javax.swing.JCheckBox chk_incideX;
    private javax.swing.JCheckBox chk_incideY;
    private javax.swing.JCheckBox chk_quadrante1;
    private javax.swing.JCheckBox chk_quadrante2;
    private javax.swing.JCheckBox chk_quadrante3;
    private javax.swing.JCheckBox chk_quadrante4;
    private javax.swing.JLabel lb_eixox;
    private javax.swing.JLabel lb_eixoy;
    private javax.swing.JLabel lb_posicao;
    private javax.swing.JTextField tf_eixox;
    private javax.swing.JTextField tf_eixoy;
    // End of variables declaration//GEN-END:variables
}
