/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author jg_la
 */
public class NewJFrame extends javax.swing.JFrame {

    LocalDate data;

    int diaAtual;
    int mesAtual;
    int anoAtual;

    double saldoTotal = 0;

    Gerenciamento g;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        data = LocalDate.now();

        diaAtual = data.getDayOfMonth();
        mesAtual = data.getMonthValue();
        anoAtual = data.getYear();

        try {
            g = new Gerenciamento(diaAtual, mesAtual, anoAtual, "src//dados.csv");
        } catch (IllegalArgumentException e) {
            exibirMensagemErro(e.getMessage());
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jp_movimentacao = new javax.swing.JPanel();
        lb_diaIncluir = new javax.swing.JLabel();
        tf_diaIncluir = new javax.swing.JTextField();
        lb_valorIncluir = new javax.swing.JLabel();
        tf_valorIncluir = new javax.swing.JTextField();
        lb_tipoIncluir = new javax.swing.JLabel();
        cb_tipoIncluir = new javax.swing.JComboBox<>();
        rb_movimentacaoReceita = new javax.swing.JRadioButton();
        rb_movimentacaoDespesa = new javax.swing.JRadioButton();
        tf_mesIncluir = new javax.swing.JTextField();
        lb_mes = new javax.swing.JLabel();
        lb_ano = new javax.swing.JLabel();
        tf_anoIncluir = new javax.swing.JTextField();
        btn_incluirMovimentacao = new javax.swing.JButton();
        jp_consulta = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_consulta = new javax.swing.JTable();
        rb_consultaReceita = new javax.swing.JRadioButton();
        rb_consultaDespesa = new javax.swing.JRadioButton();
        cb_tipoConsulta = new javax.swing.JComboBox<>();
        lb_consulta = new javax.swing.JLabel();
        rb_consultaTodos = new javax.swing.JRadioButton();
        tf_diaConsulta = new javax.swing.JTextField();
        lb_diaConsulta = new javax.swing.JLabel();
        lb_mesConsulta = new javax.swing.JLabel();
        tf_mesConsulta = new javax.swing.JTextField();
        lb_anoConsulta = new javax.swing.JLabel();
        tf_anoConsulta = new javax.swing.JTextField();
        btn_consultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_movimentacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimentação"));

        lb_diaIncluir.setText("Dia");

        lb_valorIncluir.setText("Valor");

        lb_tipoIncluir.setText("Tipo de Receita");

        cb_tipoIncluir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salário", "Décimo Terceiro", "Férias", "Outros" }));

        buttonGroup1.add(rb_movimentacaoReceita);
        rb_movimentacaoReceita.setSelected(true);
        rb_movimentacaoReceita.setText("Receita");
        rb_movimentacaoReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnReceitaSelecionado(evt);
            }
        });

        buttonGroup1.add(rb_movimentacaoDespesa);
        rb_movimentacaoDespesa.setText("Despesa");
        rb_movimentacaoDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnDespesaSelecionado(evt);
            }
        });

        tf_mesIncluir.setToolTipText("");

        lb_mes.setText("Mes");

        lb_ano.setText("Ano");

        btn_incluirMovimentacao.setText("Incluir Movimentação");
        btn_incluirMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnIncluirMovimentacao(evt);
            }
        });

        javax.swing.GroupLayout jp_movimentacaoLayout = new javax.swing.GroupLayout(jp_movimentacao);
        jp_movimentacao.setLayout(jp_movimentacaoLayout);
        jp_movimentacaoLayout.setHorizontalGroup(
            jp_movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_movimentacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_movimentacaoLayout.createSequentialGroup()
                        .addGroup(jp_movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_movimentacaoLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lb_valorIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_valorIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jp_movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_tipoIncluir)
                            .addComponent(cb_tipoIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jp_movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_movimentacaoReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_movimentacaoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(jp_movimentacaoLayout.createSequentialGroup()
                        .addGroup(jp_movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_diaIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_movimentacaoLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lb_diaIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_mesIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jp_movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_anoIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_movimentacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_incluirMovimentacao)
                .addGap(30, 30, 30))
        );
        jp_movimentacaoLayout.setVerticalGroup(
            jp_movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_movimentacaoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(rb_movimentacaoReceita)
                .addGap(3, 3, 3)
                .addComponent(rb_movimentacaoDespesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_incluirMovimentacao)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_movimentacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_movimentacaoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lb_ano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_anoIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tf_diaIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jp_movimentacaoLayout.createSequentialGroup()
                            .addGroup(jp_movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lb_mes)
                                .addComponent(lb_diaIncluir))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_mesIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jp_movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_valorIncluir)
                    .addComponent(lb_tipoIncluir))
                .addGap(6, 6, 6)
                .addGroup(jp_movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_valorIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipoIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        jp_consulta.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta"));

        jt_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Tipo", "Data", "Valor", "Saldo"
            }
        ));
        jScrollPane2.setViewportView(jt_consulta);

        buttonGroup2.add(rb_consultaReceita);
        rb_consultaReceita.setSelected(true);
        rb_consultaReceita.setText("Receita");
        rb_consultaReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnReceitaSelecionadoConsulta(evt);
            }
        });

        buttonGroup2.add(rb_consultaDespesa);
        rb_consultaDespesa.setText("Despesa");
        rb_consultaDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnDespesaSelecionadoConsulta(evt);
            }
        });

        cb_tipoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Salário", "Décimo Terceiro", "Férias", "Outros" }));
        cb_tipoConsulta.setPreferredSize(new java.awt.Dimension(122, 22));

        lb_consulta.setText("Tipo de Receita");

        buttonGroup2.add(rb_consultaTodos);
        rb_consultaTodos.setText("Todos");
        rb_consultaTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnTodosSelecionadoConsulta(evt);
            }
        });

        lb_diaConsulta.setText("Dia");

        lb_mesConsulta.setText("Mes");

        lb_anoConsulta.setText("Ano");

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnConsultarMovimentacoes(evt);
            }
        });

        javax.swing.GroupLayout jp_consultaLayout = new javax.swing.GroupLayout(jp_consulta);
        jp_consulta.setLayout(jp_consultaLayout);
        jp_consultaLayout.setHorizontalGroup(
            jp_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_consultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jp_consultaLayout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(jp_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_consultaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_consultaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_consulta)
                            .addComponent(cb_tipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_consultaTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_diaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_diaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_mesConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_mesConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_anoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_anoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_consultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jp_consultaLayout.setVerticalGroup(
            jp_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_consultaLayout.createSequentialGroup()
                .addGroup(jp_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_consultaLayout.createSequentialGroup()
                        .addContainerGap(7, Short.MAX_VALUE)
                        .addGroup(jp_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_consultaLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jp_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_mesConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_anoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lb_mesConsulta)
                                .addComponent(lb_anoConsulta)))
                        .addGap(114, 114, 114)
                        .addComponent(btn_consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jp_consultaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jp_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_consultaLayout.createSequentialGroup()
                                .addComponent(rb_consultaReceita)
                                .addGap(7, 7, 7)
                                .addComponent(rb_consultaDespesa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_consultaTodos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_consulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_tipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_consultaLayout.createSequentialGroup()
                                .addComponent(lb_diaConsulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_diaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_movimentacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_consulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_movimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jp_consulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OnReceitaSelecionado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnReceitaSelecionado
        lb_tipoIncluir.setText("Tipo de Receita");

        cb_tipoIncluir.removeAllItems();

        String[] receitas = {"Salário", "Décimo Terceiro", "Férias", "Outros"};

        for (String s : receitas) {
            cb_tipoIncluir.addItem(s);
        }
    }//GEN-LAST:event_OnReceitaSelecionado

    private void OnDespesaSelecionado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnDespesaSelecionado
        lb_tipoIncluir.setText("Tipo de Despesa");

        cb_tipoIncluir.removeAllItems();

        String[] despesas = {"Alimentação", "Transporte", "Residência", "Saúde", "Educação", "Entreterimento", "Outros"};

        for (String s : despesas) {
            cb_tipoIncluir.addItem(s);
        }
    }//GEN-LAST:event_OnDespesaSelecionado

    private void OnReceitaSelecionadoConsulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnReceitaSelecionadoConsulta
        lb_consulta.setText("Tipo de Receita");

        cb_tipoConsulta.removeAllItems();

        String[] receitas = {"Todos", "Salário", "Décimo Terceiro", "Férias", "Outros"};

        for (String s : receitas) {
            cb_tipoConsulta.addItem(s);
        }

        cb_tipoConsulta.enable(true);
    }//GEN-LAST:event_OnReceitaSelecionadoConsulta

    private void OnDespesaSelecionadoConsulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnDespesaSelecionadoConsulta
        lb_consulta.setText("Tipo de Despesa");

        cb_tipoConsulta.removeAllItems();

        String[] despesas = {"Todos", "Alimentação", "Transporte", "Residência", "Saúde", "Educação", "Entreterimento", "Outros"};

        for (String s : despesas) {
            cb_tipoConsulta.addItem(s);
        }

        cb_tipoConsulta.enable(true);
    }//GEN-LAST:event_OnDespesaSelecionadoConsulta

    private void OnTodosSelecionadoConsulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnTodosSelecionadoConsulta
        cb_tipoConsulta.enable(false);
    }//GEN-LAST:event_OnTodosSelecionadoConsulta

    private void OnIncluirMovimentacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnIncluirMovimentacao
        int dia;
        int mes;
        int ano;
        double valor;
        ITipoMovimentacao tipo = null;

        try {
            dia = Integer.parseInt(tf_diaIncluir.getText().trim());
            mes = Integer.parseInt(tf_mesIncluir.getText().trim());
            ano = Integer.parseInt(tf_anoIncluir.getText().trim());

            valor = Double.parseDouble(tf_valorIncluir.getText().trim());
        } catch (NumberFormatException e) {
            exibirMensagemErro("Erro nos valores fornecidos.");
            return;
        }

        Movimentacao m;

        int indexSelecionado = cb_tipoIncluir.getSelectedIndex();

        if (rb_movimentacaoReceita.isSelected()) {
            switch (indexSelecionado) {
                case 0:
                    tipo = TipoReceita.SALARIO;
                    break;
                case 1:
                    tipo = TipoReceita.DECIMO_TERCEIRO;
                    break;
                case 2:
                    tipo = TipoReceita.FERIAS;
                    break;
                case 3:
                    tipo = TipoReceita.OUTROS;
                    break;
            }
            try {
                m = new Receita(dia, mes, ano, valor, ((TipoReceita) tipo));
                g.incluirMovimentacao(m);
            } catch (IllegalArgumentException e) {
                exibirMensagemErro(e.getMessage());
            }

        } else if (rb_movimentacaoDespesa.isSelected()) {
            switch (indexSelecionado) {
                case 0:
                    tipo = TipoDespesa.ALIMENTACAO;
                    break;
                case 1:
                    tipo = TipoDespesa.TRANSPORTE;
                    break;
                case 2:
                    tipo = TipoDespesa.RESIDENCIA;
                    break;
                case 3:
                    tipo = TipoDespesa.SAUDE;
                    break;
                case 4:
                    tipo = TipoDespesa.EDUCACAO;
                    break;
                case 5:
                    tipo = TipoDespesa.ENTRETERIMENTO;
                    break;
                case 6:
                    tipo = TipoDespesa.OUTROS;
                    break;
            }

            try {
                m = new Despesa(dia, mes, ano, valor, ((TipoDespesa) tipo));
                g.incluirMovimentacao(m);
            } catch (IllegalArgumentException e) {
                exibirMensagemErro(e.getMessage());
            }
        }
    }//GEN-LAST:event_OnIncluirMovimentacao

    private void OnConsultarMovimentacoes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnConsultarMovimentacoes
        DefaultTableModel tabela = (DefaultTableModel) jt_consulta.getModel();

        ((DefaultTableModel) tabela).setRowCount(0);

        int diaConsulta = g.getDiaAtual();
        int mesConsulta = g.getMesAtual();
        int anoConsulta = g.getAnoAtual();

        // filtragem data
        try {
            if (!tf_diaConsulta.getText().trim().equals("")) {
                diaConsulta = Integer.parseInt(tf_diaConsulta.getText().trim());
            }

            if (!tf_mesConsulta.getText().trim().equals("")) {
                mesConsulta = Integer.parseInt(tf_mesConsulta.getText().trim());
            }

            if (!tf_anoConsulta.getText().trim().equals("")) {
                anoConsulta = Integer.parseInt(tf_anoConsulta.getText().trim());
            }

            if (diaConsulta > 31 || diaConsulta < 1 || mesConsulta > 12 || mesConsulta < 1 || anoConsulta < 1) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            exibirMensagemErro("Erro nos valores de data informados.");
            return;
        } 

        Movimentacao mFiltro = new Receita(diaConsulta, mesConsulta, anoConsulta, 0.1, null);

        ITipoMovimentacao tipoSelecionado;
        saldoTotal = 0;

        int indexCBSelecionado = cb_tipoConsulta.getSelectedIndex();
        // receita
        if (rb_consultaReceita.isSelected()) {
            // filtragem tipo
            switch (indexCBSelecionado) {
                case 1:
                    tipoSelecionado = TipoReceita.SALARIO;
                    break;
                case 2:
                    tipoSelecionado = TipoReceita.DECIMO_TERCEIRO;
                    break;
                case 3:
                    tipoSelecionado = TipoReceita.FERIAS;
                    break;
                case 4:
                    tipoSelecionado = TipoReceita.OUTROS;
                    break;
                default:
                    tipoSelecionado = null;
                    break;
            }

            for (Receita r : g.getReceitas()) {

                if (mFiltro.compareTo(r) >= 0) {
                    if (tipoSelecionado == null) {
                        Object[] dados = popularDados(r);
                        tabela.addRow(dados);
                    } else if (r.getTipo() == tipoSelecionado) {
                        Object[] dados = popularDados(r);
                        tabela.addRow(dados);
                    }
                }
            }
        } else if (rb_consultaDespesa.isSelected()) /*despesa*/ {
            // filtragem tipo
            switch (indexCBSelecionado) {
                case 1:
                    tipoSelecionado = TipoDespesa.ALIMENTACAO;
                    break;
                case 2:
                    tipoSelecionado = TipoDespesa.TRANSPORTE;
                    break;
                case 3:
                    tipoSelecionado = TipoDespesa.RESIDENCIA;
                    break;
                case 4:
                    tipoSelecionado = TipoDespesa.SAUDE;
                    break;
                case 5:
                    tipoSelecionado = TipoDespesa.EDUCACAO;
                    break;
                case 6:
                    tipoSelecionado = TipoDespesa.ENTRETERIMENTO;
                    break;
                case 7:
                    tipoSelecionado = TipoDespesa.OUTROS;
                    break;
                default:
                    tipoSelecionado = null;
                    break;
            }

            for (Despesa d : g.getDespesas()) {
                if (mFiltro.compareTo(d) >= 0) {
                    if (tipoSelecionado == null) {
                        Object[] dados = popularDados(d);
                        tabela.addRow(dados);
                    } else if (d.getTipo() == tipoSelecionado) {
                        Object[] dados = popularDados(d);
                        tabela.addRow(dados);
                    }
                }
            }
        } else {
            for (Movimentacao m : g.getMovimentacoes()) {
                if (mFiltro.compareTo(m) >= 0) {
                    Object[] dados = popularDados(m);
                    tabela.addRow(dados);
                }
            }
        }
    }//GEN-LAST:event_OnConsultarMovimentacoes

    private Object[] popularDados(Movimentacao m) {
        String dt = m.getData();
        double valor = m.getValor();
        ITipoMovimentacao tipo;
        String categoria;

        if (m instanceof Despesa) {
            categoria = "Despesa";
            tipo = ((Despesa) m).getTipo();
            saldoTotal -= valor;
        } else {
            categoria = "Receita";
            tipo = ((Receita) m).getTipo();
            saldoTotal += valor;
        }

        Object[] dados = {categoria, tipo, dt, valor, saldoTotal};
        return dados;
    }

    private void exibirMensagemErro(String erro) {
        JOptionPane.showMessageDialog(null, erro, "Erro", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_incluirMovimentacao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_tipoConsulta;
    private javax.swing.JComboBox<String> cb_tipoIncluir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jp_consulta;
    private javax.swing.JPanel jp_movimentacao;
    private javax.swing.JTable jt_consulta;
    private javax.swing.JLabel lb_ano;
    private javax.swing.JLabel lb_anoConsulta;
    private javax.swing.JLabel lb_consulta;
    private javax.swing.JLabel lb_diaConsulta;
    private javax.swing.JLabel lb_diaIncluir;
    private javax.swing.JLabel lb_mes;
    private javax.swing.JLabel lb_mesConsulta;
    private javax.swing.JLabel lb_tipoIncluir;
    private javax.swing.JLabel lb_valorIncluir;
    private javax.swing.JRadioButton rb_consultaDespesa;
    private javax.swing.JRadioButton rb_consultaReceita;
    private javax.swing.JRadioButton rb_consultaTodos;
    private javax.swing.JRadioButton rb_movimentacaoDespesa;
    private javax.swing.JRadioButton rb_movimentacaoReceita;
    private javax.swing.JTextField tf_anoConsulta;
    private javax.swing.JTextField tf_anoIncluir;
    private javax.swing.JTextField tf_diaConsulta;
    private javax.swing.JTextField tf_diaIncluir;
    private javax.swing.JTextField tf_mesConsulta;
    private javax.swing.JTextField tf_mesIncluir;
    private javax.swing.JTextField tf_valorIncluir;
    // End of variables declaration//GEN-END:variables
}
